run:
  concurrency: 4
  timeout: 3m
  modules-download-mode: vendor

linters:
  enable-all: true
  disable:
    # Annoying
    - exhaustive
    # Deprecated
    - maligned
    - scopelint
    - golint
    - interfacer
    # Useless
    - cyclop
    - dupl
    - exhaustivestruct
    - godot
    - godox
    - gomnd
    - nlreturn
    - paralleltest
    - testpackage
    - tparallel
    - thelper
    - whitespace
    - wrapcheck
    - wsl

linters-settings:
  gci:
    local-prefixes: github.com/ShoshinNikita/budget-manager/v2
  funlen:
    lines: 80
  tagliatelle:
    case:
      rules:
        json: snake

issues:
  exclude:
    # Ignore underscores in test functions
    - "use underscores in Go names; (?:func|type) (?:T|t)est"

  exclude-rules:
    - linters:
        - goerr113
      text: "do not define dynamic errors"

    - linters:
        - funlen
        - lll
      path: _test\.go

  # Display all issues
  max-issues-per-linter: 0
  max-same-issues: 0
