run:
  concurrency: 4
  build-tags:
    - integration
  modules-download-mode: vendor

linters:
  enable-all: true
  disable:
    - dupl
    - exhaustivestruct
    - godot
    - godox
    - gomnd
    - nlreturn
    - paralleltest
    - tparallel
    - testpackage
    - whitespace
    - wrapcheck
    - wsl

linters-settings:
  gci:
    local-prefixes: github.com/ShoshinNikita/budget-manager
  funlen:
    lines: 80

issues:
  exclude:
    # Ignore underscores in package names
    - "use(?: an)? underscores? in package names?"
    # Ignore underscores in test functions
    - "use underscores in Go names; (?:func|type) (?:T|t)est"
    # Ignore long functions in tests
    - "Function '(?:T|t)est.*' is too long"
    # Ignore warnings about 'github.com/go-pg/pg' specific field 'tableName'
    - "`tableName` is unused"

  exclude-rules:
    - linters:
        - goerr113
      text: "do not define dynamic errors"

  # Display all issues
  max-issues-per-linter: 0
  max-same-issues: 0
