run:
  concurrency: 4
  build-tags:
    - integration
  modules-download-mode: vendor

linters:
  enable-all: true
  disable:
    - dupl
    - godot
    - godox
    - gomnd
    - testpackage
    - whitespace
    - wsl

linters-settings:
  funlen:
    lines: 80

issues:
  exclude:
    # Ignore underscores in package names
    - "use(?: an)? underscores? in package names?"
    # Ignore underscores in test functions
    - "use underscores in Go names; (?:func|type) (?:T|t)est"
    # Ignore long functions in tests
    - "Function '(?:T|t)est.*' is too long"

  exclude-rules:
    - linters:
        - goerr113
      text: "do not define dynamic errors"

  # Display all issues
  max-issues-per-linter: 0
  max-same-issues: 0
