run:
  concurrency: 4
  timeout: 3m
  modules-download-mode: vendor

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - asciicheck
    - bodyclose
    - dogsled
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - exportloopref
    - gci
    - goconst
    - gocritic
    - goerr113
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - misspell
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - sqlclosecheck
    - tagliatelle
    - unconvert
    - unparam
    - wastedassign

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/ShoshinNikita/budget-manager/v2)
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: snake

issues:
  exclude:
    # Ignore underscores in test functions
    - "use underscores in Go names; (?:func|type) (?:T|t)est"

  exclude-rules:
    - linters:
        - goerr113
      text: "do not define dynamic errors"

  # Display all issues
  max-issues-per-linter: 0
  max-same-issues: 0
