run:
  concurrency: 4
  build-tags:
    - integration

linters:
  enable-all: true
  disable:
    - wsl
    - dupl
    - godox

linters-settings:
  funlen:
    lines: 80

issues:
  exclude:
    # Ignore underscores in test functions
    - "use underscores in Go names; (?:func|type) (?:T|t)est"
    # Ignore long functions in tests
    - "Function '(?:T|t)est.*' is too long"

  # Display all issues
  max-issues-per-linter: 0
  max-same-issues: 0
