# This config is used to build code and publish Docker images on push to the master branch
project_name: budget-manager

release:
  disable: true

changelog:
  skip: true

builds:
  - skip: true

dockers:
  - dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/shoshinnikita/{{ .ProjectName }}:master"
    build_flag_templates:
      - "--build-arg=LDFLAGS=-s -w -X 'main.version=master' -X 'main.gitHash={{ .ShortCommit }}'"
    extra_files:
      # Dirs
      - cmd/
      - internal/
      - static/
      - templates/
      - vendor/
      # Files
      - go.mod
      - go.sum
