version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      # Empty password
      # POSTGRES_PASSWORD
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./var/pg-data:/var/lib/postgresql/data"
    command: -c "log_statement=all"
