version: "2.4"

services:
  budget-manager:
    image: budget-manager:latest
    env_file:
      - .env
    # Overwrite env variables from .env
    environment:
      DB_PG_HOST: postgres
      DB_PG_PORT: 5432
      DB_PG_USER: postgres
      DB_PG_PASSWORD: postgres
      DB_PG_DATABASE: postgres
      DB_SQLITE_PATH: /srv/var/budget-manager.db
      #
      SERVER_USE_EMBED: "true"
    volumes:
      - ./_var/sqlite:/srv/var # store SQLite db in ./_var/sqlite
    ports:
      - "8080:8080"

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./_var/pg_data:/var/lib/postgresql/data # store the data in ./var/pg_data
    command: -c "log_statement=all"
