version: "3"
services:
  budget_manager:
    build:
      context: ../..
      dockerfile: ./scripts/docker/Dockerfile

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      # Empty password
      # POSTGRES_PASSWORD
      POSTGRES_DB: postgres
    volumes:
      - "./var/pg-data:/var/lib/postgresql/data"
    command: -c "log_statement=all"
