name: check code
on:
  push:
    paths-ignore:
      - "docs/**"
      - "scripts/**"
      - "static/**"
      - "templates/**"
      - "tools/**"
      - "README.md"

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - uses: actions/checkout@v2

      - name: Run integration tests
        run: make test-integ

  lint:
    name: lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - uses: actions/checkout@v2

      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.37
          skip-go-installation: true
