name: Check code
on:
  push:
    paths-ignore:
      - "templates/**"
      - "static/**"
      - "tools/**"
      - "README.md"

jobs:
  check-code:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Install golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b ${GITHUB_WORKSPACE} v1.21.0

      - name: Lint
        run: |
          PATH="${PATH}:${GITHUB_WORKSPACE}"
          make lint

      - name: Run integration tests
        run: make test-integ
