name: Release

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      GORELEASER_CONFIG: ".goreleaser.master.yml"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # GoReleaser forces snapshot mode if a tag is dirty. So, tag the last commit to bypass this behavior
      # https://github.com/goreleaser/goreleaser-action/blob/master/src/main.ts#L34
      - name: Bypass GoReleaser check
        if: ${{ contains(github.ref, 'refs/heads/') }}
        run: git tag v0.0.0-bypass-snapshot-mode

      - name: Update GoReleaser config
        if: ${{ contains(github.ref, 'refs/tags/') }}
        run: echo "GORELEASER_CONFIG=.goreleaser.yml" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.155.0
          args: release --rm-dist --config=${{ env.GORELEASER_CONFIG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
