name: Check code
on:
  push:
  pull_request:

jobs:
  check-code:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Lint
        run: make lint

      - name: Run integration tests
        run: make test-integ
